# -*- coding: utf-8 -*-
# Kernteksten lachgasbrabant.nl: homepage, bezorggebied-index en de vier regio-hubs.

HOME = {
    "title": "Lachgas bestellen in Brabant | 24/7 bezorgd via WhatsApp",
    "description": "Lachgastanks 2KG, 4KG en 10KG verzegeld bezorgd in heel Noord-Brabant. Bestel 24/7 via WhatsApp, prijs vooraf bevestigd, betalen bij levering. 18+.",
    "kicker": "24/7 bezorging in heel Noord-Brabant",
    "h1": "Lachgas bestellen en bezorgen in heel Brabant",
    "lead": "Van Bergen op Zoom tot Boxmeer en van Werkendam tot Budel: we bezorgen verzegelde lachgastanks aan de deur in heel Noord-Brabant. Je bestelt via WhatsApp en krijgt vooraf een tijdvak bevestigd.",
    "checks": [
        "Verzegelde tanks van 2KG, 4KG en 10KG",
        "Prijs en tijdvak vooraf bevestigd via WhatsApp",
        "Betalen contant of via Tikkie bij levering",
    ],
    "card_title": "In het kort",
    "card_facts": [
        ["Bezorggebied", "Heel Noord-Brabant, alle 56 gemeenten"],
        ["Levertijd", "Meestal 15 tot 25 minuten, vooraf bevestigd"],
        ["Bestellen", "Dag en nacht via WhatsApp"],
        ["Leeftijd", "Uitsluitend 18+, legitimatie bij twijfel"],
    ],
    "usps": [
        ["clock", "24 uur per dag bereikbaar", "Ook 's nachts en in het weekend reageren we op je bericht en plannen we de levering in."],
        ["pin", "Vier regio's, één werkwijze", "West, Midden, Noordoost en Zuidoost: dezelfde aanpak in Breda, Tilburg, Den Bosch en Eindhoven als in de dorpen."],
        ["tank", "Verzegeld geleverd", "Elke tank komt met intacte zegel aan de deur; je controleert hem samen met de bezorger."],
        ["shield", "Altijd 18+", "We leveren alleen aan volwassenen en vragen bij twijfel om een geldig identiteitsbewijs."],
    ],
    "regions_h2": "Bezorgen in vier Brabantse regio's",
    "regions_text": "We werken vanuit vier regio's, zodat er in heel Noord-Brabant een bezorger in de buurt is. Per gebied zie je welke plaatsen we bedienen; de levertijd is overal meestal 15 tot 25 minuten.",
    "cities_h2": "De grootste steden van Brabant",
    "cities_text": "Ook in de grote steden staan we meestal binnen 15 tot 25 minuten voor de deur. Kies je plaats voor de wijken die we bedienen, praktische informatie over de bezorging en antwoorden op veelgestelde vragen.",
    "city_slugs": ["eindhoven", "tilburg", "breda", "s-hertogenbosch", "helmond", "oss", "roosendaal", "bergen-op-zoom", "veldhoven", "waalwijk", "oosterhout", "uden"],
    "tanks_h2": "Lachgastanks in drie maten",
    "tanks_text": "We bezorgen uitsluitend complete tanks met 2, 4 of 10 kilo N2O, altijd verzegeld. Patronen en crackers verkopen we niet. Twijfel je over de maat, dan denken we via WhatsApp met je mee.",
    "steps_h2": "Zo werkt bestellen",
    "steps_text": "Geen webshop en geen account: een WhatsApp-gesprek is genoeg. In drie stappen staat de tank bij je voor de deur.",
    "steps": [
        ["Stuur je bestelling", "App ons je adres, de gewenste maat en het aantal tanks. We kijken direct of je adres in een van onze vier regio's ligt."],
        ["Bevestiging vooraf", "Je krijgt de prijs en een tijdvak terug in hetzelfde gesprek. Pas na jouw akkoord gaat de bezorger op weg."],
        ["Levering aan de deur", "De bezorger controleert bij twijfel je leeftijd, jij controleert de zegel en je betaalt contant of via Tikkie."],
    ],
    "why_h2": "Waarom Lachgas Brabant",
    "why_text": "Geen loze beloften, wel duidelijkheid over levertijd, leeftijd en regels. Dit zijn de drie punten waar je ons op mag aanspreken.",
    "why_cards": [
        ["/service/bezorgtijden-per-regio/", "Eerlijke levertijden", "Overal in Brabant meestal binnen 15 tot 25 minuten. We noemen vooraf een tijdvak en melden het meteen als het later wordt.", "Over de bezorgtijd"],
        ["/service/leeftijdscontrole-18-plus/", "Strikt 18+", "Zonder geldig identiteitsbewijs bij twijfel leveren we niet. Dat geldt op elk adres in Brabant, ook bij een feest of evenement.", "Over de leeftijdscontrole"],
        ["/informatie/is-lachgas-legaal-in-nederland/", "Open over de regels", "Lachgas staat sinds 2023 op lijst II van de Opiumwet. We leggen uit wat dat betekent en verwijzen naar de officiële bronnen.", "Wat de wet zegt"],
    ],
    "info_h2": "Informatie en achtergrond",
    "info_text": "Lees voor je bestelt wat lachgas is, wat de wet zegt en hoe je een tank bewaart en inlevert. Nuchtere uitleg, zonder verkooppraat.",
    "info_slugs": ["wat-is-lachgas", "is-lachgas-legaal-in-nederland", "lachgas-regels-per-gemeente-brabant", "lachgastank-bewaren-en-vervoeren", "lege-lachgastank-inleveren-brabant", "lachgas-bijwerkingen-en-eerste-hulp"],
    "faq_h2": "Veelgestelde vragen",
    "faq_text": "De vragen die klanten uit Brabant ons het vaakst stellen. Staat jouw vraag er niet bij, kijk dan bij alle veelgestelde vragen of stel hem via WhatsApp.",
    "faq": [
        ["Hoe bestel ik lachgas in Brabant?",
         """Je stuurt ons een WhatsApp-bericht met je adres, de gewenste tankmaat en het aantal. Wij bevestigen de prijs en een tijdvak, en na jouw akkoord gaat de bezorger op weg. Een uitleg stap voor stap vind je bij <a href="/service/bestellen-via-whatsapp/">bestellen via WhatsApp</a>."""],
        ["Hoe snel bezorgen jullie in mijn regio?",
         """In heel Noord-Brabant meestal binnen 15 tot 25 minuten, of je nu in Eindhoven woont of in een kerkdorp in de Peel. Op drukke avonden, met carnaval of bij slecht weer kan het iets langer duren; dat laten we je dan vooraf via WhatsApp weten. Het precieze tijdvak bevestigen we altijd vooraf; kijk per plaats op <a href="/bezorggebied/">het bezorggebied</a>."""],
        ["Wat kost een lachgastank?",
         """De prijs hangt af van de maat (2KG, 4KG of 10KG) en het aantal tanks. Je krijgt het bedrag vooraf in je WhatsApp-gesprek bevestigd, zodat er aan de deur geen verrassingen zijn. Wat je in het gesprek leest, is wat je bij levering betaalt."""],
        ["Hoe kan ik betalen?",
         """Je betaalt bij levering, contant of via Tikkie. Vooruitbetalen is niet nodig en vragen we ook niet. Meer over de afhandeling lees je bij <a href="/service/betalen-bij-levering/">betalen bij levering</a>."""],
        ["Moet ik mijn leeftijd aantonen?",
         """Ja. We leveren uitsluitend aan personen van 18 jaar en ouder en de bezorger vraagt bij twijfel om een geldig identiteitsbewijs. Kun je dat niet laten zien, dan gaat de tank mee terug. Lees waarom bij <a href="/service/leeftijdscontrole-18-plus/">leeftijdscontrole 18+</a>."""],
        ["Hoe zit het met de wet rond lachgas?",
         """Lachgas staat sinds 1 januari 2023 op lijst II van de Opiumwet. Verkoop en bezit voor recreatief gebruik zijn verboden; voor medische, technische en voedingstoepassingen gelden uitzonderingen, en gemeenten kunnen in hun APV aanvullende regels stellen. We leggen het uit bij <a href="/informatie/is-lachgas-legaal-in-nederland/">is lachgas legaal in Nederland</a> en verwijzen voor de actuele wettekst naar rijksoverheid.nl."""],
    ],
}

AREA_INDEX = {
    "title": "Bezorggebied Lachgas Brabant | Alle plaatsen per regio",
    "description": "Alle plaatsen in Noord-Brabant waar we lachgastanks bezorgen, verdeeld over vier regio's met de gebruikelijke levertijd per gebied. 24/7 via WhatsApp.",
    "h1": "Bezorggebied: heel Noord-Brabant",
    "lead": "Van de Biesbosch tot de Peel en van de Brabantse Wal tot het Land van Cuijk. Kies je regio of plaats en zie welke kernen we bedienen, overal meestal binnen 15 tot 25 minuten.",
    "intro": [
        """Noord-Brabant is van west naar oost ruim honderd kilometer breed. Om dat hele gebied goed te bedienen, delen we de provincie op in vier regio's: West-Brabant rond Breda, Bergen op Zoom en Roosendaal; Midden-Brabant rond Tilburg en Waalwijk; Noordoost-Brabant rond 's-Hertogenbosch, Oss en Meierijstad; en Zuidoost-Brabant rond Eindhoven, Helmond en de Kempen. Elke regio heeft een eigen pagina met de gemeenten en kernen die we bedienen. Samen dekken ze alle 56 gemeenten van de provincie, van de grote stad tot het kleinste kerkdorp.""",
        """In alle vier de regio's geldt dezelfde levertijd: meestal binnen 15 tot 25 minuten na je bestelling. Dat geldt voor de grote steden en hun buurgemeenten, voor kernen als Oss, Waalwijk, Roosendaal of Veghel en net zo goed voor het Land van Cuijk, de Kempen of Altena. Op drukke momenten, zoals vrijdag- en zaterdagavond, carnaval of een groot evenement, en bij slecht weer, files of wegwerkzaamheden kan het iets langer duren. Het blijft een indicatie: het tijdvak dat we in WhatsApp bevestigen is wat telt, en loopt het uit, dan hoor je dat vooraf van ons.""",
        """Bestellen gaat in elke regio hetzelfde. Je stuurt via WhatsApp je adres, de gewenste maat uit ons <a href="/lachgas-tanks/">assortiment lachgastanks</a> en het aantal. Wij controleren of het adres binnen het gebied valt, bevestigen de prijs en noemen een tijdvak. De bezorger levert de tank verzegeld aan de deur, controleert bij twijfel je leeftijd en je betaalt contant of via Tikkie. Ligt je adres net buiten een kern die hier staat, stuur dan toch een bericht: vaak kunnen we gewoon bezorgen. Hoe we de levertijd inschatten, lees je bij <a href="/service/bezorgtijden-per-regio/">bezorgtijden per regio</a>.""",
    ],
    "faq": [
        ["Bezorgen jullie echt in heel Noord-Brabant?",
         """Ja, alle 56 gemeenten vallen binnen het gebied en overal is de levertijd meestal 15 tot 25 minuten. Op de regiopagina's zie je per gemeente welke kernen we bedienen."""],
        ["Mijn dorp staat niet in de lijst, kan ik toch bestellen?",
         """Waarschijnlijk wel. De lijsten noemen de grootste kernen, maar de meeste kleine kernen en buurtschappen ertussen bedienen we ook. Stuur je adres via WhatsApp, dan hoor je direct of en hoe snel we kunnen komen."""],
        ["Ik verblijf op een vakantiepark of camping in Brabant, kan ik daar bestellen?",
         """Dat kan, zolang het adres in Noord-Brabant ligt en de bezorger je persoonlijk kan treffen. Stuur de naam van het park en je huisje- of plaatsnummer mee; bij een slagboom of receptie spreken we vooraf af waar je de bezorger opvangt. De leeftijdscontrole geldt er net zo goed, lees meer bij <a href="/service/bestellen-via-whatsapp/">bestellen via WhatsApp</a>."""],
        ["Bezorgen jullie ook over de provinciegrens?",
         """Ons gebied is Noord-Brabant. Adressen vlak over de grens in Gelderland, Limburg of Zeeland beoordelen we per geval; stuur je adres en we laten eerlijk weten of het past."""],
        ["Geldt de leeftijdscontrole overal hetzelfde?",
         """Ja. Of je nu in het centrum van Eindhoven woont of in een buurtschap bij Steenbergen: we leveren alleen aan 18+ en vragen bij twijfel een geldig identiteitsbewijs. Lees meer bij <a href="/service/leeftijdscontrole-18-plus/">leeftijdscontrole 18+</a>."""],
    ],
}

HUBS = [
    {
        "slug": "west-brabant",
        "name": "West-Brabant",
        "title": "Lachgas bezorgen in West-Brabant | Breda tot Bergen op Zoom",
        "description": "Lachgastanks bezorgd in West-Brabant: Breda, Roosendaal, Bergen op Zoom, Etten-Leur en alle 16 gemeenten. Meestal 15-25 min, 24/7 via WhatsApp.",
        "h1": "Lachgas bezorgen in West-Brabant",
        "lead": "Van de Biesbosch tot de Brabantse Wal en van Moerdijk tot de Belgische grens: in alle zestien West-Brabantse gemeenten bezorgen we verzegelde tanks aan de deur.",
        "card": "Breda, Roosendaal en Bergen op Zoom plus de dorpen ertussen, van Altena tot Woensdrecht.",
        "intro": [
            """West-Brabant is de brede westhoek van de provincie, ingeklemd tussen Zeeland, de Zuid-Hollandse eilanden en de Belgische grens. <a href="/lachgas-bezorgen/breda/">Breda</a> is de grootste stad en ons vertrekpunt, met Oosterhout en Etten-Leur als directe buren. Verder westelijk liggen <a href="/lachgas-bezorgen/roosendaal/">Roosendaal</a> en Bergen op Zoom, met dorpen als Oudenbosch, Sint Willebrord en Halsteren ertussen. In het noorden grenzen Moerdijk, Drimmelen en Geertruidenberg aan het Hollandsch Diep en de Amer, en boven de Bergsche Maas ligt de gemeente Altena met Werkendam. Zuidelijk sluiten Zundert, Alphen-Chaam, Baarle-Nassau en Woensdrecht aan op België.""",
            """In Breda, Oosterhout en Etten-Leur rijden we meestal binnen 15 tot 25 minuten voor. Dat geldt ook voor Roosendaal, Bergen op Zoom en de dorpen eromheen, zoals Zevenbergen, Made, Zundert en Raamsdonksveer, en voor Steenbergen, Hoogerheide, Baarle-Nassau en de kernen van Altena. Staat het verkeer op de A16, A27 of A58 vast of is het een drukke avond, dan kan het iets langer duren. Die levertijd is een indicatie: het tijdvak dat we vooraf in WhatsApp bevestigen is leidend, en loopt het door verkeer of drukte uit, dan hoor je dat van ons voordat je gaat wachten.""",
            """Bestellen doe je met één WhatsApp-bericht met je adres, de maat en het aantal tanks. Welke maat past bij je bestelling lees je bij onze <a href="/lachgas-tanks/">lachgastanks</a>; voor een klein gezelschap kies je anders dan voor een groot. Wij bevestigen de prijs en het tijdvak, de bezorger levert de tank met intacte zegel af en je betaalt contant of via Tikkie. Omdat we alleen aan 18+ leveren, laat je bij twijfel een geldig identiteitsbewijs zien. Woon je in een buurtschap dat hieronder niet staat, bijvoorbeeld langs de Mark of in de polders bij Fijnaart, stuur dan gewoon je adres en we kijken wat er kan.""",
        ],
        "places": ["breda", "bergen-op-zoom", "roosendaal", "oosterhout", "etten-leur", "zevenbergen", "oudenbosch", "raamsdonksveer", "made", "zundert", "sint-willebrord", "halsteren", "steenbergen", "hoogerheide", "werkendam", "baarle-nassau"],
        "gemeenten": [
            ["Alphen-Chaam", "Alphen, Chaam, Galder, Strijbeek", "meestal binnen 15 tot 25 minuten"],
            ["Altena", "Werkendam, Sleeuwijk, Almkerk, Woudrichem, Wijk en Aalburg", "meestal binnen 15 tot 25 minuten"],
            ["Baarle-Nassau", "Baarle-Nassau, Ulicoten, Castelré", "meestal binnen 15 tot 25 minuten"],
            ["Bergen op Zoom", "Bergen op Zoom, Halsteren, Lepelstraat", "meestal binnen 15 tot 25 minuten"],
            ["Breda", "Breda, Prinsenbeek, Teteringen, Bavel, Ulvenhout", "meestal binnen 15 tot 25 minuten"],
            ["Drimmelen", "Made, Terheijden, Wagenberg, Lage Zwaluwe, Hooge Zwaluwe", "meestal binnen 15 tot 25 minuten"],
            ["Etten-Leur", "Etten-Leur centrum, De Keen, Grauwe Polder, Schoenmakershoek", "meestal binnen 15 tot 25 minuten"],
            ["Geertruidenberg", "Raamsdonksveer, Geertruidenberg, Raamsdonk", "meestal binnen 15 tot 25 minuten"],
            ["Halderberge", "Oudenbosch, Hoeven, Oud Gastel, Bosschenhoofd, Stampersgat", "meestal binnen 15 tot 25 minuten"],
            ["Moerdijk", "Zevenbergen, Klundert, Fijnaart, Willemstad, Standdaarbuiten", "meestal binnen 15 tot 25 minuten"],
            ["Oosterhout", "Oosterhout, Dorst, Den Hout, Oosteind", "meestal binnen 15 tot 25 minuten"],
            ["Roosendaal", "Roosendaal, Wouw, Heerle, Nispen, Wouwse Plantage", "meestal binnen 15 tot 25 minuten"],
            ["Rucphen", "Sint Willebrord, Rucphen, Sprundel, Schijf, Zegge", "meestal binnen 15 tot 25 minuten"],
            ["Steenbergen", "Steenbergen, Dinteloord, Kruisland, Nieuw-Vossemeer, De Heen", "meestal binnen 15 tot 25 minuten"],
            ["Woensdrecht", "Hoogerheide, Woensdrecht, Ossendrecht, Putte, Huijbergen", "meestal binnen 15 tot 25 minuten"],
            ["Zundert", "Zundert, Rijsbergen, Klein-Zundert, Wernhout, Achtmaal", "meestal binnen 15 tot 25 minuten"],
        ],
        "faq": [
            ["Bezorgen jullie ook in de dorpen rond Breda, zoals Prinsenbeek en Bavel?",
             """Ja, Prinsenbeek, Teteringen, Bavel en Ulvenhout horen bij de gemeente Breda en ook daar zijn we meestal binnen 15 tot 25 minuten aan de deur. Je vindt ze terug op de pagina van <a href="/lachgas-bezorgen/breda/">Breda</a>."""],
            ["Hoe zit het met Baarle-Nassau en de Belgische enclaves?",
             """We bezorgen op adressen in de gemeente Baarle-Nassau, dus op Nederlands grondgebied. Omdat Nederlandse en Belgische percelen er door elkaar liggen, vragen we je het volledige adres met huisnummer te sturen; de enclaves van Baarle-Hertog vallen buiten ons gebied."""],
            ["Komen jullie ook in Altena, boven de Bergsche Maas?",
             """Ja. Werkendam, Sleeuwijk, Almkerk en Woudrichem bedienen we vanuit Breda via de A27, meestal binnen 15 tot 25 minuten. Kleinere kernen als Hank, Dussen en Wijk en Aalburg kunnen ook; stuur je adres en we noemen een tijdvak."""],
            ["Kan ik laten bezorgen in de binnenstad van Bergen op Zoom of Roosendaal?",
             """Ja. In de oude centra zijn veel straten autoluw en is parkeren lastig, dus noem in je bericht het huisnummer en een handig punt om elkaar te treffen, zoals de ingang van je portiek. Bij een appartement vragen we je beneden te komen of de bezorger binnen te laten, waarna aan de deur de zegel en bij twijfel je leeftijd worden gecontroleerd."""],
            ["Kan ik in West-Brabant ook 's nachts of in het weekend bestellen?",
             """Ja, we zijn in alle vier de regio's dag en nacht bereikbaar via WhatsApp. Op vrijdag- en zaterdagavond is het druk, dus bestel dan liever wat eerder; lees meer bij <a href="/service/weekendbezorging/">weekendbezorging</a>."""],
        ],
    },
    {
        "slug": "midden-brabant",
        "name": "Midden-Brabant",
        "title": "Lachgas bezorgen in Midden-Brabant | Tilburg en Waalwijk",
        "description": "Lachgastanks aan de deur in Midden-Brabant: Tilburg, Waalwijk, Goirle, Oisterwijk, Dongen en de Langstraat. Vooraf bevestigd tijdvak, 24/7 via WhatsApp.",
        "h1": "Lachgas bezorgen in Midden-Brabant",
        "lead": "Tilburg en de ring van dorpen eromheen, de Langstraat van Waalwijk tot Vlijmen en de bossen richting Hilvarenbeek: negen gemeenten, één bezorgservice.",
        "card": "Tilburg, Waalwijk en de Langstraat, van Goirle en Rijen tot Kaatsheuvel en Drunen.",
        "intro": [
            """Midden-Brabant, in de regio zelf vaak Hart van Brabant genoemd, draait om <a href="/lachgas-bezorgen/tilburg/">Tilburg</a>, qua inwoners de tweede stad van de provincie. De ring eromheen is compact: Goirle en Berkel-Enschot liggen tegen de stad aan, Rijen, Udenhout en Oisterwijk op een kwartier rijden. Ten noorden ligt de Langstraat, de keten van <a href="/lachgas-bezorgen/waalwijk/">Waalwijk</a>, Sprang-Capelle, Kaatsheuvel, Drunen en Vlijmen langs de A59, met de Loonse en Drunense Duinen ertussen. Dongen sluit westelijk aan op Oosterhout, terwijl Hilvarenbeek en Diessen zuidelijk in het buitengebied richting de Belgische grens liggen. Negen gemeenten in totaal, dicht op elkaar en goed ontsloten.""",
            """Tilburg zelf, Berkel-Enschot, Goirle en Rijen bedienen we meestal binnen 15 tot 25 minuten. Hetzelfde geldt voor Waalwijk, Dongen, Oisterwijk, Kaatsheuvel, Udenhout, Drunen en Vlijmen, die via de N261 en de A59 vlot bereikbaar zijn, en voor Hilvarenbeek en de dorpen richting de grens. In de spits en op zaterdagavond kan het iets langer duren; dan krijg je vooraf een aangepaste tijdsindicatie. We noemen altijd eerst een tijdvak via WhatsApp en houden ons daaraan zo goed als het verkeer toelaat.""",
            """Bestellen gaat snel: stuur ons via WhatsApp je adres in Midden-Brabant, de maat die je wilt en het aantal tanks. Op <a href="/lachgas-tanks/">onze tankpagina</a> staat wat 2KG, 4KG en 10KG inhouden, zodat je de maat kiest die bij je bestelling past. We bevestigen de prijs voordat er iemand vertrekt, en aan de deur betaal je contant of via Tikkie. De bezorger levert de tank met intacte zegel en vraagt bij twijfel om je identiteitsbewijs; onder de 18 leveren we niet, ook niet in de studentenbuurten van Tilburg. Vragen over een adres in het buitengebied, bijvoorbeeld bij Moergestel of Haghorst? App het, dan kijken we mee.""",
        ],
        "places": ["tilburg", "waalwijk", "dongen", "goirle", "oisterwijk", "drunen", "kaatsheuvel", "rijen", "vlijmen", "berkel-enschot", "udenhout", "hilvarenbeek"],
        "gemeenten": [
            ["Dongen", "Dongen, 's Gravenmoer, Klein-Dongen, Dongen-Vaart", "meestal binnen 15 tot 25 minuten"],
            ["Gilze en Rijen", "Rijen, Gilze, Hulten, Molenschot", "meestal binnen 15 tot 25 minuten"],
            ["Goirle", "Goirle, Riel", "meestal binnen 15 tot 25 minuten"],
            ["Heusden", "Vlijmen, Drunen, Nieuwkuijk, Haarsteeg, Heusden", "meestal binnen 15 tot 25 minuten"],
            ["Hilvarenbeek", "Hilvarenbeek, Diessen, Esbeek, Haghorst, Biest-Houtakker", "meestal binnen 15 tot 25 minuten"],
            ["Loon op Zand", "Kaatsheuvel, Loon op Zand, De Moer", "meestal binnen 15 tot 25 minuten"],
            ["Oisterwijk", "Oisterwijk, Moergestel, Haaren, Heukelom", "meestal binnen 15 tot 25 minuten"],
            ["Tilburg", "Tilburg, Berkel-Enschot, Udenhout, Biezenmortel", "meestal binnen 15 tot 25 minuten"],
            ["Waalwijk", "Waalwijk, Sprang-Capelle, Waspik", "meestal binnen 15 tot 25 minuten"],
        ],
        "faq": [
            ["Vallen Berkel-Enschot en Udenhout onder Tilburg?",
             """Ja, beide dorpen horen sinds 1997 bij de gemeente Tilburg, net als Biezenmortel sinds 2021. Berkel-Enschot ligt tegen de stad aan, Udenhout iets noordelijker; in beide dorpen zijn we meestal binnen 15 tot 25 minuten."""],
            ["Bezorgen jullie in de hele Langstraat?",
             """Ja: Waalwijk, Sprang-Capelle, Waspik, Kaatsheuvel, Drunen, Vlijmen en Nieuwkuijk horen er allemaal bij. De A59 rijgt de kernen aan elkaar, en we bevestigen er meestal een tijdvak van 15 tot 25 minuten na je bestelling."""],
            ["Ik woon in Goirle of Riel, hoe snel zijn jullie er?",
             """Goirle grenst direct aan Tilburg-Zuid en ook in Riel, iets westelijker, zijn we meestal binnen 15 tot 25 minuten aan de deur. Duurt het door drukte of slecht weer iets langer, dan melden we dat vooraf. Bekijk de details op <a href="/lachgas-bezorgen/goirle/">Goirle</a>."""],
            ["Rijden jullie ook naar Hilvarenbeek, Diessen en Esbeek?",
             """Ja, ook in het zuidelijkste stuk van de regio rekenen we meestal op 15 tot 25 minuten. Noem bij een adres in het buitengebied een herkenningspunt, dan vindt de bezorger je meteen. Zit je in Hilvarenbeek zelf, kijk dan op <a href="/lachgas-bezorgen/hilvarenbeek/">de pagina van Hilvarenbeek</a>."""],
            ["Is bezorgen tijdens de Tilburgse Kermis of carnaval anders?",
             """Op drukke dagen, zoals de kermis in juli of carnaval, kan het iets langer duren dan de gebruikelijke 15 tot 25 minuten; we bevestigen tijdvakken dan strikt op volgorde van binnenkomst en melden vooraf als het later wordt. Reserveren voor een datum kan via WhatsApp; de leeftijdscontrole blijft dan gewoon gelden. Zie <a href="/service/feestdagen-en-evenementen/">feestdagen en evenementen</a>."""],
        ],
    },
    {
        "slug": "noordoost-brabant",
        "name": "Noordoost-Brabant",
        "title": "Lachgas bezorgen in Noordoost-Brabant | Den Bosch en Oss",
        "description": "Lachgastanks bezorgd in Noordoost-Brabant: 's-Hertogenbosch, Oss, Veghel, Uden, Boxtel en het Land van Cuijk. Meestal 15-25 min, 24/7 via WhatsApp.",
        "h1": "Lachgas bezorgen in Noordoost-Brabant",
        "lead": "Van de Bossche binnenstad tot de Maas bij Grave en Boxmeer: tien gemeenten, waaronder Meierijstad, Maashorst en Land van Cuijk, overal meestal binnen 15 tot 25 minuten.",
        "card": "'s-Hertogenbosch, Oss, Veghel en Uden tot aan de Maas bij Cuijk, Grave en Boxmeer.",
        "intro": [
            """Noordoost-Brabant strekt zich uit van <a href="/lachgas-bezorgen/s-hertogenbosch/">'s-Hertogenbosch</a>, de provinciehoofdstad, tot aan de Maas die de grens met Gelderland en Limburg vormt. Direct rond Den Bosch liggen Rosmalen, Vught en Sint-Michielsgestel; via de A59 en de A50 kom je bij <a href="/lachgas-bezorgen/oss/">Oss</a>, Heesch en de Maashorst met Uden. Meierijstad bundelt Veghel, Schijndel en Sint-Oedenrode, met Boxtel aan de zuidwestkant. Het Land van Cuijk is de uitloper langs de Maas met Cuijk, Grave en Boxmeer. Een landelijke regio met een paar flinke kernen en veel kerkdorpen ertussen.""",
            """In Den Bosch, Rosmalen en Vught zijn we meestal binnen 15 tot 25 minuten aan de deur. Dat geldt ook voor Oss, Veghel, Schijndel, Sint-Oedenrode, Uden, Boxtel, Heesch en Sint-Michielsgestel, stevige kernen die goed bereikbaar zijn via de A2, A50 en A59, en voor Cuijk, Grave, Boxmeer en Boekel aan de rand van de regio. Bij evenementen in de Bossche binnenstad, slecht weer of wegwerkzaamheden kan het iets langer duren. Daarom bevestigen we altijd eerst een tijdvak en melden we het vooraf als het uitloopt.""",
            """Bestellen begint met een WhatsApp-bericht waarin je je adres, de maat en het aantal noemt. Kijk vooraf bij de <a href="/lachgas-tanks/">lachgastanks</a> welke inhoud bij je bestelling past: 2KG, 4KG of 10KG, alle drie verzegeld. Na onze bevestiging van de prijs en het tijdvak komt de bezorger naar je deur, laat de intacte zegel zien en vraagt bij twijfel je identiteitsbewijs. Betalen doe je contant of via Tikkie. Woon je in een kerkdorp als Nuland, Erp, Zeeland of Mill, stuur dan je adres: meestal kunnen we ook daar binnen 15 tot 25 minuten komen.""",
        ],
        "places": ["s-hertogenbosch", "oss", "veghel", "uden", "rosmalen", "schijndel", "boxtel", "vught", "sint-oedenrode", "heesch", "sint-michielsgestel", "cuijk", "boxmeer", "grave", "boekel"],
        "gemeenten": [
            ["Bernheze", "Heesch, Heeswijk-Dinther, Nistelrode, Vorstenbosch, Loosbroek", "meestal binnen 15 tot 25 minuten"],
            ["Boekel", "Boekel, Venhorst", "meestal binnen 15 tot 25 minuten"],
            ["Boxtel", "Boxtel, Liempde, Lennisheuvel, Esch", "meestal binnen 15 tot 25 minuten"],
            ["'s-Hertogenbosch", "'s-Hertogenbosch, Rosmalen, Empel, Engelen, Nuland", "meestal binnen 15 tot 25 minuten"],
            ["Land van Cuijk", "Cuijk, Boxmeer, Grave, Mill, Sint Anthonis", "meestal binnen 15 tot 25 minuten"],
            ["Maashorst", "Uden, Volkel, Zeeland, Schaijk, Odiliapeel", "meestal binnen 15 tot 25 minuten"],
            ["Meierijstad", "Veghel, Schijndel, Sint-Oedenrode, Erp, Zijtaart", "meestal binnen 15 tot 25 minuten"],
            ["Oss", "Oss, Berghem, Ravenstein, Lith, Geffen", "meestal binnen 15 tot 25 minuten"],
            ["Sint-Michielsgestel", "Sint-Michielsgestel, Berlicum, Den Dungen, Gemonde, Middelrode", "meestal binnen 15 tot 25 minuten"],
            ["Vught", "Vught, Cromvoirt, Helvoirt", "meestal binnen 15 tot 25 minuten"],
        ],
        "faq": [
            ["Horen Rosmalen, Empel en Nuland bij Den Bosch?",
             """Ja, het zijn kernen van de gemeente 's-Hertogenbosch. Rosmalen en Empel grenzen aan de stad, Nuland en Vinkel liggen oostelijker; in al die kernen zijn we meestal binnen 15 tot 25 minuten. Zie ook <a href="/lachgas-bezorgen/rosmalen/">Rosmalen</a>."""],
            ["Bezorgen jullie overal in Meierijstad?",
             """Ja. Veghel, Schijndel en Sint-Oedenrode zijn de drie hoofdkernen en zitten meestal binnen 15 tot 25 minuten. Erp, Zijtaart, Boerdonk en de andere kerkdorpen bedienen we ook, eveneens meestal binnen 15 tot 25 minuten."""],
            ["Hoe werkt het in het Land van Cuijk?",
             """Het is een uitgestrekte gemeente aan de Maas met veel kleine kernen. Cuijk, Grave, Boxmeer, Mill en Sint Anthonis vallen meestal binnen 15 tot 25 minuten. Bestel je voor een vast tijdstip, geef dat dan ruim vooraf door."""],
            ["Wat is Maashorst precies en hoort Uden daarbij?",
             """Maashorst is de gemeente die in 2022 ontstond uit Uden en Landerd, genoemd naar het natuurgebied ertussen. Uden is de grootste kern en valt meestal binnen 15 tot 25 minuten; Zeeland, Schaijk, Volkel en Odiliapeel bedienen we ook. Meer op <a href="/lachgas-bezorgen/uden/">Uden</a>."""],
            ["Kan ik in Oss ook laat op de avond bestellen?",
             """Ja, ook in Oss, Berghem en Ravenstein zijn we dag en nacht bereikbaar. Na middernacht sturen we een bericht zodra we voor de deur staan en bellen we alleen aan als jij dat wilt. Lees hoe dat gaat bij <a href="/service/nachtbezorging/">nachtbezorging</a>."""],
        ],
    },
    {
        "slug": "zuidoost-brabant",
        "name": "Zuidoost-Brabant",
        "title": "Lachgas bezorgen in Zuidoost-Brabant | Eindhoven en Helmond",
        "description": "Lachgastanks bezorgd in Zuidoost-Brabant: Eindhoven en stadsdelen, Helmond, Veldhoven, de Kempen en de Peel. Vooraf bevestigd tijdvak, 24/7 via WhatsApp.",
        "h1": "Lachgas bezorgen in Zuidoost-Brabant",
        "lead": "Eindhoven met alle stadsdelen, Helmond, Veldhoven en de dorpen van de Kempen tot de Peel: 21 gemeenten, overal meestal binnen 15 tot 25 minuten bezorgd.",
        "card": "Eindhoven, Helmond en Veldhoven plus de Kempen en de Peel, van Bladel tot Deurne en Budel.",
        "intro": [
            """Zuidoost-Brabant is de dichtstbevolkte hoek van de provincie, met <a href="/lachgas-bezorgen/eindhoven/">Eindhoven</a> als grootste stad van Brabant in het midden. We bezorgen in alle stadsdelen, van Woensel en Strijp tot Tongelre, Stratum en Gestel, en in de kring eromheen: Veldhoven, Best, Son en Breugel, Nuenen, Geldrop en Waalre. Oostelijk ligt <a href="/lachgas-bezorgen/helmond/">Helmond</a>, met de Peeldorpen Deurne, Asten, Someren en Gemert erachter. Westelijk en zuidelijk begint de Kempen: Oirschot, Eersel, Bladel, Reusel, Bergeijk en Valkenswaard, tot aan Budel bij de Limburgse en Belgische grens.""",
            """Eindhoven en de buurgemeenten Veldhoven, Best, Nuenen, Son en Breugel, Waalre en Geldrop vallen meestal binnen 15 tot 25 minuten, net als Helmond. Dat geldt ook voor Valkenswaard, Mierlo, Deurne, Gemert, Someren, Asten, Eersel, Heeze, Oirschot en Beek en Donk, die via de A2, A67, A50 en A270 goed bereikbaar zijn, en voor Bladel, Reusel, Bergeijk en Budel aan de rand van de Kempen. Kost de Ring van Eindhoven in de spits extra tijd, dan melden we vooraf dat het iets langer duurt. Alles blijft een indicatie: het bevestigde tijdvak in WhatsApp is wat telt.""",
            """Bestellen is in Zuidoost-Brabant niet anders dan elders: je appt ons je adres, de gewenste maat en het aantal. Vergelijk de inhoud van 2KG, 4KG en 10KG op de pagina <a href="/lachgas-tanks/">lachgastanks</a> als je twijfelt. We bevestigen de prijs en een tijdvak, waarna de bezorger de verzegelde tank bij je aflevert; je betaalt contant of via Tikkie en laat bij twijfel een geldig identiteitsbewijs zien. Een studentenhuis in Eindhoven behandelen we niet anders dan een rijtjeshuis in Mierlo: zonder 18+ geen levering. Woon je in een kerkdorp als Lieshout, Knegsel of Maarheeze, stuur dan je adres en we noemen een tijdvak.""",
        ],
        "places": ["eindhoven", "woensel", "strijp", "tongelre", "stratum", "gestel", "helmond", "veldhoven", "geldrop", "valkenswaard", "best", "deurne", "nuenen", "waalre", "son-en-breugel", "oirschot", "gemert", "someren", "asten", "mierlo", "heeze", "eersel", "beek-en-donk", "bladel", "bergeijk", "budel", "reusel"],
        "gemeenten": [
            ["Asten", "Asten, Ommel, Heusden (gemeente Asten)", "meestal binnen 15 tot 25 minuten"],
            ["Bergeijk", "Bergeijk, Luyksgestel, Westerhoven, Riethoven, Weebosch", "meestal binnen 15 tot 25 minuten"],
            ["Best", "Best centrum, Wilhelminadorp, Heuveleind, Salderes", "meestal binnen 15 tot 25 minuten"],
            ["Bladel", "Bladel, Hapert, Hoogeloon, Casteren, Netersel", "meestal binnen 15 tot 25 minuten"],
            ["Cranendonck", "Budel, Maarheeze, Soerendonk, Budel-Schoot, Budel-Dorplein", "meestal binnen 15 tot 25 minuten"],
            ["Deurne", "Deurne, Liessel, Vlierden, Neerkant, Helenaveen", "meestal binnen 15 tot 25 minuten"],
            ["Eersel", "Eersel, Duizel, Steensel, Knegsel, Vessem", "meestal binnen 15 tot 25 minuten"],
            ["Eindhoven", "Woensel, Strijp, Tongelre, Stratum, Gestel", "meestal binnen 15 tot 25 minuten"],
            ["Geldrop-Mierlo", "Geldrop, Mierlo", "meestal binnen 15 tot 25 minuten"],
            ["Gemert-Bakel", "Gemert, Bakel, Handel, De Mortel, Milheeze", "meestal binnen 15 tot 25 minuten"],
            ["Heeze-Leende", "Heeze, Leende, Sterksel, Leenderstrijp", "meestal binnen 15 tot 25 minuten"],
            ["Helmond", "Helmond centrum, Brandevoort, Mierlo-Hout, Stiphout, Brouwhuis", "meestal binnen 15 tot 25 minuten"],
            ["Laarbeek", "Beek en Donk, Aarle-Rixtel, Lieshout, Mariahout", "meestal binnen 15 tot 25 minuten"],
            ["Nuenen c.a.", "Nuenen, Gerwen, Nederwetten, Eeneind", "meestal binnen 15 tot 25 minuten"],
            ["Oirschot", "Oirschot, Spoordonk, Middelbeers, Oostelbeers, Westelbeers", "meestal binnen 15 tot 25 minuten"],
            ["Reusel-De Mierden", "Reusel, Hooge Mierde, Lage Mierde, Hulsel", "meestal binnen 15 tot 25 minuten"],
            ["Someren", "Someren, Someren-Eind, Someren-Heide, Lierop", "meestal binnen 15 tot 25 minuten"],
            ["Son en Breugel", "Son, Breugel", "meestal binnen 15 tot 25 minuten"],
            ["Valkenswaard", "Valkenswaard, Dommelen, Borkel en Schaft", "meestal binnen 15 tot 25 minuten"],
            ["Veldhoven", "Veldhoven-Dorp, Meerveldhoven, Zeelst, Oerle, Heikant", "meestal binnen 15 tot 25 minuten"],
            ["Waalre", "Waalre, Aalst", "meestal binnen 15 tot 25 minuten"],
        ],
        "faq": [
            ["Bezorgen jullie in alle stadsdelen van Eindhoven?",
             """Ja, in Woensel, Strijp, Tongelre, Stratum, Gestel en het centrum zijn we meestal binnen 15 tot 25 minuten, en in Meerhoven en Acht net zo goed. Elk stadsdeel heeft een eigen pagina, bijvoorbeeld <a href="/lachgas-bezorgen/woensel/">Woensel</a>."""],
            ["Bezorgen jullie in alle wijken van Helmond?",
             """Ja, van het centrum tot Brandevoort, Mierlo-Hout, Stiphout, Rijpelberg, Dierdonk en Brouwhuis, meestal binnen 15 tot 25 minuten. Mierlo zelf hoort bij de gemeente Geldrop-Mierlo en bedienen we ook. Bij een appartement in Brandevoort helpt het als je vooraf zegt welke ingang de bezorger moet nemen."""],
            ["Hoe ver gaan jullie de Kempen in?",
             """Tot aan de Belgische grens. In Eersel, Oirschot en Valkenswaard rekenen we meestal op 15 tot 25 minuten, en in Bladel, Hapert, Reusel, Bergeijk en Luyksgestel ook. Zie bijvoorbeeld de pagina van <a href="/lachgas-bezorgen/bladel/">Bladel</a>."""],
            ["En de Peel: Deurne, Asten, Someren en Gemert?",
             """Die bedienen we vanuit de kant van Helmond, meestal binnen 15 tot 25 minuten, ook in Liessel, Neerkant, Bakel en Someren-Eind in het buitengebied. Kijk voor details op <a href="/lachgas-bezorgen/deurne/">Deurne</a>."""],
            ["Mag een lege tank bij het restafval in Eindhoven of Helmond?",
             """Nee, een lege tank is een drukhouder en hoort bij de milieustraat van je eigen gemeente, niet in de container of de glasbak. Bewaar hem rechtop tot je hem wegbrengt. Wat we verder adviseren lees je bij <a href="/informatie/lege-lachgastank-inleveren-brabant/">lege lachgastank inleveren</a>."""],
        ],
    },
]
